const seed = {applications: [], leads: []};
let data = JSON.parse(localStorage.getItem('northstar-data') || 'null') || {...seed,settings:{roles:'WordPress|Virtual Assistant|Tech VA|DNS management|Web Admin|Data Entry|AI-assisted',frequency:'Every 6 hours'}};
data.settings=data.settings||{roles:'WordPress|Virtual Assistant|Tech VA|DNS management|Web Admin|Data Entry|AI-assisted',frequency:'Every 6 hours'};
let appPage=1;let leadPage=1;const APP_PAGE_SIZE=6;const LEAD_PAGE_SIZE=6;
let pendingConfirmation=null;
async function checkServerStatus(){const status=$('#server-status'),dot=status?.querySelector('.status-dot');try{const response=await fetch('/api/state',{cache:'no-store'});if(!response.ok)throw new Error('offline');dot?.classList.add('online');dot?.classList.remove('offline');status?.setAttribute('title','Server online');status?.setAttribute('aria-label','Server status: online')}catch(error){dot?.classList.add('offline');dot?.classList.remove('online');status?.setAttribute('title','Server offline');status?.setAttribute('aria-label','Server status: offline')}}
setInterval(checkServerStatus,10000);
window.addEventListener('load',checkServerStatus);
const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];
document.addEventListener('DOMContentLoaded',()=>{const grid=document.querySelector('.settings-grid');if(grid&&grid.children.length>1)grid.prepend(grid.children[1]);const settingsSubhead=document.querySelector('#settings-view .subhead');if(settingsSubhead)settingsSubhead.textContent='Shape your search preferences.';const leadGrid=$('#lead-grid'),loadMore=document.createElement('button');loadMore.id='load-more-leads';loadMore.className='button secondary';loadMore.textContent='Load more';leadGrid.after(loadMore);loadMore.addEventListener('click',()=>{leadPage++;renderLeads()});const pagination=document.createElement('div');pagination.id='applications-pagination';pagination.className='table-pagination';$('#applications-view .table-card').after(pagination)});
function save(){localStorage.setItem('northstar-data',JSON.stringify(data));return fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}).then(r=>r.ok?r.json():Promise.reject()).then(serverData=>{data=serverData;localStorage.setItem('northstar-data',JSON.stringify(data));return serverData}).catch(()=>null)}
function currentView(){const path=location.pathname.slice(1);return ['overview','applications','leads','inbox','settings'].includes(path)?path:(['overview','applications','leads','inbox','settings'].includes(location.hash.slice(1))?location.hash.slice(1):'overview')}
async function loadState(){const loadingStarted=performance.now();try{const response=await fetch('/api/state');if(!response.ok)throw new Error('API unavailable');data=await response.json();localStorage.setItem('northstar-data',JSON.stringify(data))}catch(error){}render();renderRoles();setupApiKeyField();if(data.settings?.resume_name)$('#resume-name').textContent=data.settings.resume_name;setupResumeControls();updateResumeControls();setupFrequencyDropdown();navigate(currentView(),false);if(currentView()==='inbox'&&data.inbox?.integration?.outlook_connected)syncOutlook();await new Promise(resolve=>setTimeout(resolve,Math.max(0,500-(performance.now()-loadingStarted))));document.querySelector('#page-loader')?.classList.add('is-hidden')}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function initials(name){return name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function todayLabel(){return new Date().toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}
function formatFollowup(value){if(!value)return '';const date=new Date(`${value}T00:00:00`);return Number.isNaN(date.getTime())?value:date.toLocaleDateString('en-US',{month:'short',day:'numeric'})}
function renderStats(){const a=data.applications, active=a.filter(x=>!['Rejected','Withdrawn'].includes(x.status)).length, interviews=a.filter(x=>['Interview scheduled','Interviewed','Offer'].includes(x.status)).length, response=a.length?Math.round(interviews/a.length*100):0;$('#stat-grid').innerHTML=[['Active applications',active,'Keep the momentum'],['Interviews',interviews,'Across your pipeline'],['Response rate',`${response}%`,'From submitted applications'],['Leads',data.leads.length,'Ready to review']].map(x=>`<div class="stat"><div class="stat-label">${x[0]}</div><div class="stat-value">${x[1]}</div><div class="stat-detail">${x[2]}</div></div>`).join('');$('#hero-count').textContent=`${active} active application${active===1?'':'s'}`;$('#application-count').textContent=a.length;$('#lead-count').textContent=data.leads.length;$('#inbox-count').textContent=data.inbox?.unread||0;$('#chart-total').textContent=`${a.length} total`}
function renderChart(){const range=Number($('#chart-range')?.value?.match(/\d+/)?.[0]||30),now=new Date(),bucketSize=Math.ceil(range/5),counts=Array(5).fill(0);data.applications.forEach(application=>{const date=new Date(application.date);if(Number.isNaN(date.getTime()))return;const age=Math.floor((now-date)/(24*60*60*1000));if(age>=0&&age<range)counts[Math.min(4,Math.floor((range-1-age)/bucketSize))]++});const max=Math.max(...counts,1);$('#chart').innerHTML=counts.map((count,i)=>`<div class="bar ${i===4?'current':''}${count?'':' empty'}" style="height:${count?Math.max(12,Math.round(count/max*92)):0}%"></div>`).join('')}
function renderFollowups(){const list=[...data.applications].filter(x=>x.follow).sort((a,b)=>String(a.follow).localeCompare(String(b.follow))).slice(0,3);$('#follow-up-list').innerHTML=list.length?list.map(x=>`<div class="follow-item"><div class="follow-icon">${initials(x.company)}</div><div class="follow-copy"><strong>${x.title}</strong><small>${x.company}</small></div><span class="follow-date">${formatFollowup(x.follow)}</span></div>`).join(''):'<div class="empty-state">No follow-ups yet.</div>'}
function pill(status){let c=status==='Interview scheduled'||status==='Offer'?'teal-pill':status==='Applied'?'orange-pill':'';return `<span class="pill ${c}">${status}</span>`}
function renderApplications(){const query=($('#application-search')?.value||'').toLowerCase(),status=$('#status-filter')?.value||'all',category=$('#category-filter')?.value||'all';const rows=data.applications.filter(x=>(status==='all'||x.status===status)&&(category==='all'||x.category===category)&&(`${x.title} ${x.company}`).toLowerCase().includes(query));const pages=Math.max(1,Math.ceil(rows.length/APP_PAGE_SIZE));if(appPage>pages)appPage=pages;const visible=rows.slice((appPage-1)*APP_PAGE_SIZE,appPage*APP_PAGE_SIZE),statuses=['Applied','Interview scheduled','Interviewed','Offer','Rejected','Withdrawn'];$('#applications-body').innerHTML=visible.map(x=>`<tr><td><div class="role-cell"><div class="company-mark">${initials(x.company)}</div><div><strong>${x.title}</strong><small>${x.company}</small></div></div></td><td><div class="status-picker"><button type="button" class="status-trigger" data-status-menu="${x.id}" aria-expanded="false">${x.status}<iconify-icon icon="lucide:chevron-down" class="ui-icon" aria-hidden="true"></iconify-icon></button><div class="status-menu hidden" data-status-options="${x.id}">${statuses.map(option=>`<button type="button" class="status-option ${option===x.status?'selected':''}" data-status-id="${x.id}" data-status-value="${option}">${option}</button>`).join('')}</div></div></td><td><span class="pill">${x.category}</span></td><td>${x.date}</td><td>${x.follow?`<span class="follow-date">${formatFollowup(x.follow)}</span>`:'—'}</td><td>${x.url?`<a class="source-link application-link" href="${x.url}" target="_blank" rel="noreferrer" aria-label="Open job posting" title="Open job posting"><iconify-icon icon="lucide:external-link" class="ui-icon" aria-hidden="true"></iconify-icon></a>`:'—'}</td><td><button class="row-menu" data-remove="${x.id}" aria-label="Delete application" title="Delete application"><iconify-icon icon="lucide:trash-2" class="ui-icon" aria-hidden="true"></iconify-icon></button></td></tr>`).join('');$('#applications-empty').classList.toggle('hidden',rows.length>0);const pagination=$('#applications-pagination');if(pagination)pagination.innerHTML=pages>1?`<button class="page-button" data-app-page="prev" ${appPage===1?'disabled':''} aria-label="Previous page"><iconify-icon icon="lucide:chevron-left" class="ui-icon" aria-hidden="true"></iconify-icon></button>${Array.from({length:pages},(_,i)=>`<button class="page-button ${appPage===i+1?'active':''}" data-app-page="${i+1}">${i+1}</button>`).join('')}<button class="page-button" data-app-page="next" ${appPage===pages?'disabled':''} aria-label="Next page"><iconify-icon icon="lucide:chevron-right" class="ui-icon" aria-hidden="true"></iconify-icon></button>`:''}
function renderLeads(){const visible=data.leads.slice(0,leadPage*LEAD_PAGE_SIZE);$('#lead-grid').innerHTML=data.leads.length?visible.map(x=>`<article class="lead-card"><div class="lead-top"><span class="pill teal-pill">${x.verified}</span><span class="pill">${x.category}</span></div><h3>${x.title}</h3><div class="lead-company">${x.company} · ${x.location}</div><p>${x.summary}</p><div class="lead-bottom"><a class="source-link" href="${x.url}" target="_blank" rel="noreferrer">View direct posting <iconify-icon icon="lucide:external-link" class="ui-icon" aria-hidden="true"></iconify-icon></a><button class="button secondary move-lead" data-lead="${x.id}">Move to applications</button></div></article>`).join(''):'<div class="empty-state">No leads. Run a search to refresh.</div>';const button=$('#load-more-leads');if(button)button.hidden=visible.length>=data.leads.length||!data.leads.length}
function escapeHtml(value){return String(value||'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function renderInbox(){const inbox=data.inbox||{},badge=$('#inbox-count'),threads=$('#inbox-thread-list'),connect=$('#outlook-connect'),sync=$('#outlook-sync'),connected=Boolean(inbox.integration?.outlook_connected);if(badge)badge.textContent=inbox.unread||0;if(connect){connect.innerHTML=connected?`<iconify-icon icon="mdi:microsoft-outlook" class="outlook-icon" aria-hidden="true"></iconify-icon>Outlook connected${inbox.integration.outlook_email?` · ${escapeHtml(inbox.integration.outlook_email)}`:''}`:'<iconify-icon icon="mdi:microsoft-outlook" class="outlook-icon" aria-hidden="true"></iconify-icon>Connect Outlook';connect.className=`outlook-connect-button ${connected?'connected':''}`;connect.disabled=connected}if(sync)sync.classList.toggle('hidden',!connected);if(threads)threads.innerHTML=(inbox.threads_detail||[]).length?(inbox.threads_detail||[]).map(thread=>`<button type="button" class="inbox-thread" data-inbox-thread="${thread.id}"><span class="inbox-thread-subject">${escapeHtml(thread.subject)}</span><span class="inbox-thread-meta">${escapeHtml(thread.last_message_at)} · ${thread.unread_count} unread</span><span class="inbox-thread-tags">${(thread.tags||[]).map(tag=>`<span class="inbox-tag" style="background:${tag.color}">${escapeHtml(tag.name)}</span>`).join('')}</span><span class="inbox-thread-snippet">${escapeHtml(thread.snippet)}</span></button>`).join(''):'<div class="empty-state">No messages received yet.</div>'}
function render(){renderStats();renderChart();renderFollowups();renderApplications();renderLeads();renderInbox();$('#last-search').textContent=data.settings?.last_search?`Last search: ${data.settings.last_search}`:'Last search: not yet run'}
function navigate(view,updatePath=true){const valid=['overview','applications','leads','inbox','settings'].includes(view)?view:'overview';$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===valid));$$('.view').forEach(x=>{const active=x.id===`${valid}-view`;x.classList.toggle('active',active);x.style.display=active?'block':'none'});$('#page-label').textContent=valid==='inbox'?'Inbox':valid[0].toUpperCase()+valid.slice(1);if(updatePath){const path=valid==='overview'?'/':`/${valid}`;if(location.pathname!==path||location.hash)history.pushState(null,'',path)}if(valid==='applications')renderApplications();if(valid==='leads')renderLeads()}
window.addEventListener('popstate',()=>navigate(currentView(),false));
document.addEventListener('change',e=>{if(e.target.id==='chart-range')renderChart()});
function renderRoles(){const roles=(data.settings?.roles||'').split('|').filter(Boolean);$('#role-tags').innerHTML=roles.map((role,i)=>`<span class="role-tag">${role}<button type="button" data-role-index="${i}" aria-label="Remove ${role}"><iconify-icon icon="lucide:x" aria-hidden="true"></iconify-icon></button></span>`).join('')}
function addRole(){const input=$('#role-input'),role=input.value.trim();if(!role)return;const roles=(data.settings?.roles||'').split('|').filter(Boolean);if(!roles.some(x=>x.toLowerCase()===role.toLowerCase())){roles.push(role);data.settings.roles=roles.join('|');input.value='';renderRoles();save()}}
function setupApiKeyField(){const urlInput=document.querySelector('input[name="url"]');if(urlInput)urlInput.placeholder='Optional posting link';document.querySelectorAll('input').forEach(input=>input.placeholder=input.placeholder.replaceAll('…',''));if($('#api-key'))return;const frequency=$('#frequency'),label=document.createElement('label');label.className='field-label api-key-field';label.innerHTML='Codex API key<div class="api-key-input-wrap" style="position:relative;display:block"><input id="api-key" type="password" placeholder="Enter your Codex API key"><button type="button" id="remove-api-key" class="remove-api-key hidden" style="position:absolute;right:8px;top:50%;transform:translateY(-50%);width:26px;height:26px;padding:0;border-radius:50%;background:transparent;color:#7a8580;font-size:20px;line-height:1" aria-label="Remove saved Codex API key" title="Remove saved Codex API key"><iconify-icon icon="lucide:x" aria-hidden="true"></iconify-icon></button></div><small id="api-key-updated" style="display:block;color:#7a8580;font-weight:400;margin-top:8px">Last updated: Not recorded</small>';frequency.parentElement.insertBefore(label,frequency.nextSibling);$('#remove-api-key').addEventListener('click',removeApiKey);updateApiKeyStatus()}
function updateApiKeyStatus(){const updated=$('#api-key-updated'),apiKey=$('#api-key'),remove=$('#remove-api-key'),active=Boolean(data.settings?.api_key_set);if(updated)updated.textContent=`Last updated: ${data.settings?.api_key_updated||'Not recorded'}`;if(apiKey){apiKey.placeholder=active?(data.settings?.api_key_hint?`Saved ${data.settings.api_key_hint}`:'Codex API key saved locally'):'Enter your Codex API key';apiKey.classList.toggle('key-stored',active)}if(remove)remove.classList.toggle('hidden',!active)}
async function removeApiKey(){const button=$('#remove-api-key');if(button)button.disabled=true;try{const response=await fetch('/api/api-key/remove',{method:'POST'}),result=await response.json();if(!response.ok)throw new Error(result.error||'Could not remove API key');data=result;localStorage.setItem('northstar-data',JSON.stringify(data));if($('#api-key'))$('#api-key').value='';updateApiKeyStatus();toast('Codex API key removed.')}catch(error){toast(error.message)}finally{if(button)button.disabled=false}}
async function saveInboxAccount(event){event.preventDefault();const form=event.target,button=form.querySelector('button[type="submit"]'),payload=Object.fromEntries(new FormData(form));button.disabled=true;button.textContent='Testing…';try{const response=await fetch('/api/inbox/account',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),result=await response.json();if(!response.ok)throw new Error(result.error||'Could not save inbox account');const test=await fetch('/api/inbox/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({account_id:result.account_id})}),testResult=await test.json();if(!test.ok)throw new Error(testResult.error||'Connection test failed');data=result.state;localStorage.setItem('northstar-data',JSON.stringify(data));renderInbox();toast('Inbox connected.')}catch(error){toast(error.message)}finally{button.disabled=false;button.textContent='Save and test connection'}}
async function syncInbox(){const button=$('#sync-inbox'),account=data.inbox?.accounts_detail?.[0];if(!account)return;button.disabled=true;button.textContent='Syncing…';try{const response=await fetch('/api/inbox/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({account_id:account.id})}),result=await response.json();if(!response.ok)throw new Error(result.error||'Inbox sync failed');data=result.state;localStorage.setItem('northstar-data',JSON.stringify(data));renderInbox();toast(`${result.imported} message${result.imported===1?'':'s'} synced.`)}catch(error){toast(error.message)}finally{button.disabled=false;button.textContent='Sync inbox'}}
async function sendInboxMessage(event){event.preventDefault();const form=event.target,button=form.querySelector('button[type="submit"]');button.disabled=true;button.textContent='Sending…';try{const payload={recipient:form.elements.recipient.value.trim(),subject:form.elements.subject.value.trim(),body:form.elements.body.value.trim(),attachments:[]};for(const file of form.elements.attachments.files){if(file.size>40*1024*1024)throw new Error(`${file.name} is too large.`);payload.attachments.push({filename:file.name,content:(await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',').pop());reader.onerror=reject;reader.readAsDataURL(file)}))})}const response=await fetch('/api/inbox/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),result=await response.json();if(!response.ok)throw new Error(result.error||'Could not send message');data=result.state;localStorage.setItem('northstar-data',JSON.stringify(data));form.reset();renderInbox();toast('Message sent.')}catch(error){toast(error.message)}finally{button.disabled=false;button.textContent='Send message'}}
async function openInboxThread(threadId){const detail=$('#inbox-thread-detail');if(!detail)return;try{const response=await fetch(`/api/inbox/thread?thread_id=${threadId}`),result=await response.json();if(!response.ok)throw new Error(result.error||'Could not load conversation');detail.innerHTML=result.messages.map(message=>`<article class="inbox-message"><div class="inbox-message-meta">${escapeHtml(message.direction)} · ${escapeHtml(message.sender)} · ${escapeHtml(message.received_at)}</div><p>${escapeHtml(message.body_text)}</p></article>`).join('');detail.classList.remove('hidden')}catch(error){toast(error.message)}}
async function syncOutlook(){const button=$('#outlook-sync');if(button){button.disabled=true;button.textContent='Syncing…'}try{const response=await fetch('/api/outlook/sync',{method:'POST'}),result=await response.json();if(!response.ok)throw new Error(result.error||'Outlook sync failed');data=result.state;localStorage.setItem('northstar-data',JSON.stringify(data));renderInbox();toast(`${result.imported} Outlook message${result.imported===1?'':'s'} imported.`)}catch(error){toast(error.message)}finally{if(button){button.disabled=false;button.textContent='Sync Outlook'}}}
function setupFrequencyDropdown(){const select=$('#frequency');if(!select||$('#frequency-trigger'))return;select.value=data.settings?.frequency||select.value;select.classList.add('native-frequency');const picker=document.createElement('div');picker.className='frequency-picker';picker.innerHTML=`<button type="button" id="frequency-trigger" class="frequency-trigger" aria-expanded="false">${select.value}<iconify-icon icon="lucide:chevron-down" class="ui-icon" aria-hidden="true"></iconify-icon></button><div class="frequency-menu hidden">${[...select.options].map(option=>`<button type="button" class="frequency-option ${option.value===select.value?'selected':''}" data-frequency-value="${option.value}">${option.textContent}</button>`).join('')}</div>`;select.after(picker);const trigger=$('#frequency-trigger'),menu=picker.querySelector('.frequency-menu');trigger.addEventListener('click',()=>{menu.classList.toggle('hidden');trigger.setAttribute('aria-expanded',String(!menu.classList.contains('hidden')))});picker.querySelectorAll('[data-frequency-value]').forEach(option=>option.addEventListener('click',()=>{select.value=option.dataset.frequencyValue;trigger.firstChild.textContent=select.value;picker.querySelectorAll('.frequency-option').forEach(item=>item.classList.toggle('selected',item===option));menu.classList.add('hidden');trigger.setAttribute('aria-expanded','false');select.dispatchEvent(new Event('change',{bubbles:true}))}))}
document.addEventListener('click',e=>{if(!e.target.closest('.frequency-picker')){$('.frequency-menu')?.classList.add('hidden');$('#frequency-trigger')?.setAttribute('aria-expanded','false')}});
document.addEventListener('click',e=>{const tableCard=document.querySelector('.table-card'),trigger=e.target.closest('[data-status-menu]');if(trigger){const menu=document.querySelector(`[data-status-options="${trigger.dataset.statusMenu}"]`);$$('.status-menu').forEach(item=>{if(item!==menu)item.classList.add('hidden')});menu?.classList.toggle('hidden');trigger.setAttribute('aria-expanded',String(menu&&!menu.classList.contains('hidden')));tableCard?.classList.toggle('status-menu-open',Boolean(menu&&!menu.classList.contains('hidden')));return}const option=e.target.closest('[data-status-value]');if(option){const application=data.applications.find(item=>item.id===Number(option.dataset.statusId));if(application){application.status=option.dataset.statusValue;save();render();toast('Application status updated.')}return}if(!e.target.closest('.status-picker')){$$('.status-menu').forEach(item=>item.classList.add('hidden'));tableCard?.classList.remove('status-menu-open')}});
document.addEventListener('change',e=>{const select=e.target.closest('[data-status-id]');if(select){const application=data.applications.find(item=>item.id===Number(select.dataset.statusId));if(application){application.status=select.value;save();renderStats();toast('Application status updated.')}}});
document.addEventListener('click',e=>{const page=e.target.closest('[data-app-page]');if(page&&!page.disabled){const pages=Math.max(1,Math.ceil(data.applications.length/APP_PAGE_SIZE));appPage=page.dataset.appPage==='prev'?Math.max(1,appPage-1):page.dataset.appPage==='next'?Math.min(pages,appPage+1):Number(page.dataset.appPage);renderApplications()}});
function setupResumeControls(){const dropZone=$('#drop-zone');if(!dropZone)return;if(!$('#resume-status')){const status=dropZone.querySelector('span')||document.createElement('span');status.id='resume-status';if(!status.parentElement)dropZone.querySelector('input')?.after(status)}if(!$('#remove-resume')){const button=document.createElement('button');button.type='button';button.id='remove-resume';button.className='button secondary remove-resume hidden';button.innerHTML='<iconify-icon icon="lucide:x" aria-hidden="true"></iconify-icon>';button.setAttribute('aria-label','Remove resume');button.title='Remove resume';button.addEventListener('click',removeResume);dropZone.append(button)}}
function updateResumeControls(){const name=$('#resume-name'),status=$('#resume-status'),button=$('#remove-resume'),hasResume=Boolean(data.settings?.resume_name);if(name&&!hasResume)name.textContent='Drop your resume here';if(status&&!status.classList.contains('analyzing'))status.textContent=hasResume?'Resume analyzed and ready for AI search.':'PDF or DOCX · max 10MB';if(button)button.classList.toggle('hidden',!hasResume)}
function setResumeAnalyzing(active){const dropZone=$('#drop-zone'),status=$('#resume-status'),button=$('#remove-resume');dropZone?.classList.toggle('analyzing',active);if(status){status.classList.toggle('analyzing',active);status.textContent=active?'Analyzing resume…':''}if(button)button.classList.toggle('hidden',active||!data.settings?.resume_name)}
async function uploadResume(file){setupResumeControls();setResumeAnalyzing(true);const reader=new FileReader();reader.onload=async()=>{try{const response=await fetch('/api/resume',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:file.name,data:reader.result})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Resume upload failed');data.settings.resume_name=file.name;save();$('#resume-name').textContent=file.name;setResumeAnalyzing(false);updateResumeControls();toast('Resume analyzed and ready for AI search.')}catch(error){setResumeAnalyzing(false);updateResumeControls();toast(error.message)}};reader.readAsDataURL(file)}
async function removeResume(){const button=$('#remove-resume');if(button)button.disabled=true;try{const response=await fetch('/api/resume/remove',{method:'POST'}),result=await response.json();if(!response.ok)throw new Error(result.error||'Could not remove resume');data=result.state;localStorage.setItem('northstar-data',JSON.stringify(data));updateResumeControls();toast('Resume removed.')}catch(error){toast(error.message)}finally{if(button)button.disabled=false}}
async function saveSettings(){data.settings.frequency=$('#frequency').value;const payload={roles:data.settings.roles||'',frequency:data.settings.frequency};const key=$('#api-key')?.value.trim();if(key)payload.api_key=key;try{const response=await fetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok)throw new Error('Save failed');data=await response.json();localStorage.setItem('northstar-data',JSON.stringify(data));if($('#api-key'))$('#api-key').value='';setupApiKeyField();updateApiKeyStatus();toast('Settings saved locally.')}catch(error){toast('Could not save settings. Is the server running?')}}
document.addEventListener('click',e=>{if(e.target.matches('[data-action="save-settings"]'))saveSettings()})
function openModal(){ $('#modal').classList.remove('hidden');$('#application-form input[name=title]').focus() }
function closeModal(){ $('#modal').classList.add('hidden') }
function openConfirmation(type,id){pendingConfirmation={type,id};const isDelete=type==='delete';$('#confirm-eyebrow').textContent=isDelete?'Delete application':'Move lead';$('#confirm-title').textContent=isDelete?'Delete this application?':'Move this lead to applications?';$('#confirm-message').textContent=isDelete?'This cannot be undone.':'This will remove the lead from your Leads queue and add it to Applications.';$('#confirm-accept').textContent=isDelete?'Delete':'Move';$('#confirm-modal').classList.remove('hidden')}
function closeConfirmation(){pendingConfirmation=null;$('#confirm-modal').classList.add('hidden')}
async function confirmPending(){if(!pendingConfirmation)return;const {type,id}=pendingConfirmation;if(type==='delete'){data.applications=data.applications.filter(x=>x.id!==id);const saved=save();render();toast('Application removed.');await saved}else{const lead=data.leads.find(x=>x.id===id);if(lead){data.applications.unshift({id:Date.now(),title:lead.title,company:lead.company,category:lead.category,status:'Applied',date:todayLabel(),follow:'',url:lead.url});data.leads=data.leads.filter(x=>x.id!==id);const saved=save();render();toast('Lead moved to applications.');await saved}}closeConfirmation()}
document.addEventListener('click',e=>{const target=e.target.closest('[data-remove],.move-lead');if(!target)return;e.preventDefault();e.stopPropagation();openConfirmation(target.matches('[data-remove]')?'delete':'move',Number(target.dataset.remove||target.dataset.lead))},true);
document.addEventListener('click',e=>{if(e.target.matches('#confirm-cancel')||e.target.id==='confirm-modal'){closeConfirmation()}if(e.target.matches('#confirm-accept'))confirmPending()});
async function runSearch(){const btn=$('[data-action=search]');btn.disabled=true;btn.innerHTML='Searching…';try{const response=await fetch('/api/search',{method:'POST'}),result=await response.json();if(!response.ok)throw new Error(result.error||'Search failed');data=result.state;localStorage.setItem('northstar-data',JSON.stringify(data));render();navigate('leads');toast(`${result.leads.length} new lead${result.leads.length===1?'':'s'} found.`)}catch(error){toast(error.message)}finally{btn.disabled=false;btn.innerHTML='<iconify-icon icon="lucide:sparkles" class="ui-icon" aria-hidden="true"></iconify-icon> Search now'}}
$$('[data-view]').forEach(el=>el.addEventListener('click',()=>navigate(el.dataset.view)));$$('[data-action=add-application]').forEach(el=>el.addEventListener('click',openModal));$$('[data-action=search]').forEach(el=>el.addEventListener('click',runSearch));$('#modal-close').addEventListener('click',closeModal);$('#cancel-modal').addEventListener('click',closeModal);$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});['application-search','status-filter','category-filter'].forEach(id=>$('#'+id).addEventListener('input',renderApplications));
$('#application-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);data.applications.unshift({id:Date.now(),title:f.get('title'),company:f.get('company'),category:f.get('category'),status:f.get('status'),date:todayLabel(),follow:f.get('follow')||'',url:f.get('url')||''});save();e.target.reset();closeModal();render();toast('Application added to your pipeline.');navigate('applications')});
document.addEventListener('click',e=>{const remove=e.target.closest('[data-remove]');if(remove){data.applications=data.applications.filter(x=>x.id!==Number(remove.dataset.remove));save();render();toast('Application removed.')}const move=e.target.closest('.move-lead');if(move){const lead=data.leads.find(x=>x.id===Number(move.dataset.lead));data.applications.unshift({id:Date.now(),title:lead.title,company:lead.company,category:lead.category,status:'Applied',date:'Sep 19, 2026',follow:'',url:lead.url});data.leads=data.leads.filter(x=>x.id!==lead.id);save();render();toast('Lead moved to applications.')}});
$('#resume-input').addEventListener('change',e=>{if(e.target.files[0])uploadResume(e.target.files[0])});$('#drop-zone').addEventListener('click',e=>{if(e.target.tagName!=='BUTTON')$('#resume-input').click()});$('#drop-zone .button').addEventListener('click',()=>$('#resume-input').click());$('#drop-zone').addEventListener('dragover',e=>{e.preventDefault();$('#drop-zone').style.background='#e3f1ed'});$('#drop-zone').addEventListener('dragleave',()=>$('#drop-zone').style.background='');$('#drop-zone').addEventListener('drop',e=>{e.preventDefault();$('#drop-zone').style.background='';if(e.dataTransfer.files[0])uploadResume(e.dataTransfer.files[0])});$('#add-role').addEventListener('click',addRole);$('#role-input').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addRole()}});document.addEventListener('click',e=>{const removeRole=e.target.closest('[data-role-index]');if(removeRole){const roles=(data.settings.roles||'').split('|').filter(Boolean);roles.splice(Number(removeRole.dataset.roleIndex),1);data.settings.roles=roles.join('|');renderRoles();save()}});$('#frequency').addEventListener('change',()=>{data.settings.frequency=$('#frequency').value;save();toast('Search frequency updated.')});$('[data-action=save-settings]').addEventListener('click',()=>{data.settings.frequency=$('#frequency').value;save()});$('#outlook-connect').addEventListener('click',()=>{if(!data.inbox?.integration?.outlook_connected)location.href='/api/outlook/connect'});$('#outlook-sync').addEventListener('click',syncOutlook);document.addEventListener('click',e=>{const thread=e.target.closest('[data-inbox-thread]');if(thread)openInboxThread(Number(thread.dataset.inboxThread))});loadState();
